language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
sudo: false
script: "make test"
env:
  global:
    - secure: "IDmkpfKbfvQ4zHuy0B8dcimuIDSa755NhLnJgQJhLTuNIaQTTno8C2iObZKUTZ8e3/DfsDr9W0zN+yXcAakPWlOyYtHVuGbNZUNkeucMc3p/Uf8yQ/QdxYYbMhEVeZd/q6sy/XqdE1zjqzW71crM44qqc500A3OpkOB6YUiDQIeBTB8OQIrlD1GH6k+KplJYlx8123LZT/k2Konfn8sSgfPE7yaI/00YtvVtpNRr/FxSpi3Y9L1j7ndtmYe+gwT2MfVbAokLyMQ9KEuXaIjvctDeXesjLkT/rapD5La6HmyISQ2nghT5taQEskIczcS3FbWdbyZX5AC1uCvEcheCsHPKu7jvq45OsbkILrgW3rNd9ox4jBoPtDLMKIo6b17axe2gnWTp+bEovJRFhJ/kLyfbezjiKK27IEfJsrhaS13GUPHekO1o4SnvgHPOYJBGwHNKSv0iH5wP/ibgM5oB3mC0XJg+Ic1IzaMf0+k2mzlF7iASEt/OPwSl2fafYN0W6a41OXNP+aNug65Z0tUSWC0wWV0m0aDPFrSpjVzD5MdwMoNAvtz/tC2DaILWPGZrb8CG9sSa0m6t7oPUKXvC2cNL1iAtL+maXxCApzSfyDk7lSKKdeesWIUWrpJdaufxl7YXcpF3KzY4+pBx5kbpJZ7eM3luzXNMnn4d1W6Wn68="
    - secure: "mSAFsSeAYomm8UVHJMtkkFY0DIW0Nhui0weZ9o+048lMM5IaunXOVU1BmW/m4s0jLa3VCxvOEdMDLuOxSzVYL1rsCa/5+UIzwg10sXPzwFCY9oyeWJ8s1LlGZJ6TJD8zLRi+PCmToxaBDPLCEWSDToniZWpD9XJnR/fPoMXmBeJsVQzKtsJEs+MUegqkQIq1jpoRZZWJ/Ut8Ih3Reu1LWMwYPaVRak0xiRLSwJZTVORxbghiLN5xKYmrGazOAIlGgu0LZzvQynAkFcsg2l3SNftyYimzeLDC2dZ6vrjjeFQt9nOs6Uyo+/wZXlcU5HCV2v488YD09N9ubXK4r52XfSj+y1nyDDQcy0qaxs+W1KIcZY9viZFV2r30EnjajntlQF6PkLUxr5lcS4EBg+jiN4CjJ/RgDVBwJrKCIWMR1AUxo19iPBD5XJTz/IGIb6QBmQ+FtvX5EEPpjrz6K1EJIZZtmOI+4TprCFWqJ2lP/teOaxp1VJV1rbGNHNJ2eTaV+Q7EriqbO5curztSR8r6Nb/VWWAOztlrmgO3uUuvLc94Ule1VQnawfU8HGjD0Zl+oH1X3Lnd2vCckjoSNskU8pAFXppDdytBjQ/LOoRg/DoauxjJZlfUyR4ckWZS3UPMDO15zpMrtgn4xDbFbvP/1mZRbwAy5gyiUH6mQgNNPsI="
    - AWS_REGION=us-west-2
